service: acg-roborover

plugins:
  - serverless-iam-roles-per-function
  - serverless-offline

provider:
  name: aws
  runtime: nodejs8.10
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}
  environment:
    REGION: ${self:provider.region}
    TELEMETRY_TABLE: telemetry-${self:provider.stage}

functions:
  - ${file(./services/telemetry/functions.yml)}
  - ${file(./services/control/functions.yml)}

resources:
  - ${file(./services/telemetry/resources.yml)}