#!/bin/bash

ENV=development
ENDPOINT=$(aws iot describe-endpoint --query endpointAddress --output text)
HOSTNAME=$(uname -a | awk '{print $2}')
SERIAL_NO=MAC_TEST
CLIENT_ID=MAC_TEST

export AWS_IOT_ENDPOINT=${ENDPOINT}
export CLIENT_ID=${CLIENT_ID}
export HOSTNAME=${HOSTNAME}
export SERIAL_NO=${SERIAL_NO}
export NODE_ENV=$ENV

node index.js -d -c MAC_TEST -m
